### ISSUE TITLE
Show direct upload image on item view

### ISSUE THREAD

**Issue by moritzebeling** [centre-for-documentary-architecture/documentary-architecture.org#103]
- ... wenn man raufgeklickt hat? Kann man da draufklicken? Wo kann man die Infos (Credits) davon sehen?
- thumbs als »Profilbild«

**Comment by annaluiseschubert** [comment]
Fragestellung ist folgende: Wenn ein _item_ als _thumb_ nicht ein _image_ aus dem Archiv hat, sondern stattdessen das _thumb_ ein _direct upload ist, wird dieses auf der Item-Einzel-Seite nicht mehr angezeigt. Im Feedback hat sich herausgestellt, dass das teilweise irritierend ist. Also ganz konkretes Beispiel: Ich sehe Liste von _persons_ im Archiv, in der kleine »Profilbildchen« dargestellt werden. Wenn ich auf eine _person_ klicke, ist aber das Portrait dieser nicht mehr zu sehen. Vielleicht seltsam. Was meinst du? Gern direkt besprechen.

**Comment by moritzebeling** [comment]
<img width="1302" alt="Bildschirmfoto 2020-12-11 um 15 13 18" src="https://user-images.githubusercontent.com/39742729/101913638-86227a00-3bc3-11eb-8e08-7c36ee472ae0.png">

**Comment by annaluiseschubert** [comment]
Hast du es mal unter der Überschrift angeordnet getestet?
