### ISSUE TITLE
Replace Quotes

### ISSUE THREAD

**Issue by annaluiseschubert** [centre-for-documentary-architecture/documentary-architecture.org#112]
Anleitung Moritz:

https://regexr.com/4os07

Regex find:
(?:")([^\s].+?[^\s])(?:") um "word" zu finden
(?:“)([^\s].+?[^\s])(?:”) um “word” zu finden
(?:„)([^\s].+?[^\s])(?:“) um „word“ zu finden
Replace:
»$1« um durch »word« zu ersetzen

Jedes einzeln überprüfen!!

-- macht Ise, aber braucht bitte nochmal Anleitung von Moritz

**Comment by moritzebeling** [comment]
hab ich eigentlich schon mal gemacht. wenn ich jetzt nochmal danach suche finde ich nix. Findest du noch was? Ansonsten kannst du das glaub ich schließen

**Comment by annaluiseschubert** [comment]
Du Held !
